---
name: test setup-python-and-poetry

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  setup-python-poetry:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: 5yutan5/test-typescript-action@main
        with:
          python-version: 3.x
      - run: poetry run python demo_python/test.py
